services:
  main:
    build:
      context: ./backend
      dockerfile: Dockerfile # this is the name of your custom docker file
    ports:
      - "5001:80" # this is an example port mapping, you can change it as needed
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=appuser
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
  stripe:
    image: "stripe/stripe-cli:latest"
    network_mode: host
    command:
        listen --api-key sk_test_51O3EaqElC8Fuz3iAlWgS4Zq4LEkBTzmSXdIrJcbc4gp2dDrduDHxab6mOTTMPpm2piLqhWgCwrOESjUUDYPImFvh00deSahasY --forward-to localhost:5001/api/payments/webhook

volumes:
  redis-data:
  postgres-data: